### ISSUE TITLE
SSL problems

### ISSUE THREAD

**Issue by mdi** [kaaes/timing#4]
This is a great bookmarklet. Thank you for that!

But it appears to not work on SSL-enabled sites. Try it on any site behind SSL, i.e. https://google.com, and the "Just a moment" indicator hangs forever.

I'm not sure what's causing this, but it would be great if it could work on these sites also!

Also, less important, what do the darker portions in the chart indicate?

**Comment by christophercurrie** [comment]
The script is being loaded from a non-SSL location, which Chrome, at least, blocks when viewing a secure page.

The bookmarklet is easily fixed by editing it to load the script from an "http://' URL, to a "protocol relative" url of the form "//kaaes.github.com/timing/timing.js".

However, fixing the bookmarklet doesn't solve the issue because kaaes.github.com doesn't accept HTTPS connections. AFAICT Github Pages doesn't support SSL, so fixing this will probably require moving the script to an SSL enabled CDN. CloudFlare might be willing. http://cdnjs.com/

**Comment by mdi** [comment]
Having it loaded from cdjs.com would be great. I looked at adding it myself, but I think it might be better if @kaaes or someone with commit access to this handles it, as cdnjs wants a proper version number, which it looks like this doesn't have yet.

**Comment by kaaes** [comment]
Hi guys,

@christophercurrie is of course right. The code is at this moment entirely on github which as far as I know doesn't support SSL for gh-pages. I am looking at cdnjs.com right now - it's a really cool idea!
I'm not sure if they will want it, but I guess it's worth trying :] 
I'll have a look nto what's necessary like versioning & minification and what not.

Thanks for bringing my attention to that topic.

**Comment by kantawala** [comment]
Changing the src to https://raw.github.com/kaaes/timing/gh-pages/profiler.js could be a work around. I tried it in the bookmarklet and it seems to work. The js gets delivered with MIME type text/plain but the script does get executed.

**Comment by kaaes** [comment]
This has been fixed a loooong time ago.
